/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: zasedvs (https://sketchfab.com/zasedvs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cat-figure-d04d8ac2c1ba47ee9e03351b4f08dd4b
Title: Cat figure
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-18.02, -19.09, -15.51]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.Texture_0} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.Texture_0} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.Texture_0} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Untextured} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
